export enum AssetType {
  SWITCHER = 'SWITCHER',
  TRANSFORMER = 'TRANSFORMER',
  METER = 'METER',
  GENERATOR = 'GENERATOR',
  SOLAR_PANEL = 'SOLAR_PANEL',
  BATTERY = 'BATTERY',
  WIND_TURBINE = 'WIND_TURBINE',
  SUBSTATION = 'SUBSTATION',
  DISTRIBUTION_BOX = 'DISTRIBUTION_BOX',
  OTHER = 'OTHER'
}
